#!/bin/bash

getent passwd gxc >/dev/null || {
  mkdir /tmp/gxcskel
  groupadd gxc
  useradd -m -d /var/lib/gxc -k /tmp/gxcskel -s /bin/false -g gxc gxc
  rmdir /tmp/gxcskel
}

mkdir -p /etc/ssl/gxc
[ ! -f /etc/ssl/gxc/gongxincoin.key ] || [ ! -f /etc/ssl/gxc/gongxincoin.crt ] && openssl req -nodes -x509 -newkey rsa:4096 -keyout /etc/ssl/gxc/gongxincoin.key -out /etc/ssl/gxc/gongxincoin.crt -days 3560 -subj /C=US/ST=Oregon/L=Portland/O=IT/CN=gongxincoin.gxc

[ -f /var/lib/gxc/.gongxincoin/gongxincoin.conf ] && exit 0

mkdir -p /var/lib/gxc/.gongxincoin
cat<<EOF >/var/lib/gxc/.gongxincoin/gongxincoin.conf
rpcuser=gxccoinrpc
rpcpassword=`pwgen 50 1`
listen=1
server=1
rpcallowip=*
rpcport=6662
maxconnections=80
gen=0
daemon=1
rpcssl=1
rpcsslcertificatechainfile=/etc/ssl/gxc/gongxincoin.crt
rpcsslprivatekeyfile=/etc/ssl/gxc/gongxincoin.key
rpcsslciphers=HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4:!SSLv2
EOF

chmod 600 /var/lib/gxc/.gongxincoin/gongxincoin.conf
chown -R gxc.gxc /var/lib/gxc/.gongxincoin

mkdir -p /etc/gongxincoin
ln -s /var/lib/gxc/.gongxincoin/gongxincoin.conf /etc/gongxincoin/gongxincoin.conf
ln -s /etc/ssl/gxc /etc/gongxincoin/certs

update-rc.d gongxincoind defaults
service gongxincoind start

exit 0
